### ISSUE TITLE
cli 与 swoole结合  报  Undefined variable: params 

### ISSUE THREAD

**Issue by aizxin** [sasou/gene#5]
PHP Fatal error:  Uncaught Exception: Undefined variable: params in :3
Stack trace:
#0 (3): Gene\Exception::doError(8, 'Undefined varia...', '', 3, Array)
#1 [internal function]: unknown()
#2 Gene\Application->run('GET', '/')
#3 {main}
  thrown in Unknown on line 3

**Comment by sasou** [comment]
swoole是什么版本，加下我QQ：407011466，详聊
